AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket

    Properties:
      BucketName: ntk-terraform
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain

  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "ntk-terraform-lock"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "LockID"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "LockID"
          KeyType: "HASH"

Outputs:
  ARN:
    Value: !GetAtt
      - S3Bucket
      - Arn
    Description: S3 bucket for Terraform state